In [1]:
import pandas as pd
import joblib

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split

In [3]:
df = pd.read_csv(
    "X:/AI-SPAM-PHISHING-DETECTOR/data/processed/final_dataset_cleaned.csv",
    keep_default_na=False
)

df.head()

,title,text,type,clean_text
0,?? the secrets to SUCCESS,"Hi James,\n\nHave you claim your complimentary...",spam,hi james claim complimentary gift yet ive comp...
1,?? You Earned 500 GCLoot Points,"\nalt_text\nCongratulations, you just earned\n...",not spam,alttext congratulation earned completed follow...
2,?? Your GitHub launch code,"Here's your GitHub launch code, @Mortyj420!\n ...",not spam,here github launch code mortyj octocat standin...
3,[The Virtual Reward Center] Re: ** Clarifications,"Hello,\n \nThank you for contacting the Virtua...",not spam,hello thank contacting virtual reward center v...
4,"10-1 MLB Expert Inside, Plus Everything You Ne...","Hey Prachanda Rawal,\n\nToday's newsletter is ...",spam,hey prachanda rawal today newsletter jampacked...

In [4]:
df["label"] = df["type"].map({
    "not spam": 0,
    "spam": 1
})

df[["type","label"]].head()

       type  label
0      spam      1
1  not spam      0
2  not spam      0
3  not spam      0
4      spam      1

In [5]:
X = df["clean_text"]

y = df["label"]

In [6]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print(X_train.shape)
print(X_test.shape)

(4680,)
(1171,)

In [7]:
tfidf = TfidfVectorizer(
    max_features=5000
)

In [8]:
X_train_tfidf = tfidf.fit_transform(X_train)

X_test_tfidf = tfidf.transform(X_test)

In [9]:
print(X_train_tfidf.shape)

print(X_test_tfidf.shape)

(4680, 5000)
(1171, 5000)

In [11]:
joblib.dump(
    tfidf,
    "X:/AI-SPAM-PHISHING-DETECTOR/models/tfidf_vectorizer.pkl"
)

print("TF-IDF Vectorizer Saved Successfully!")

TF-IDF Vectorizer Saved Successfully!

In [13]:
joblib.dump(
    X_train_tfidf,
    "X:/AI-SPAM-PHISHING-DETECTOR/models/X_train.pkl"
)

joblib.dump(
    X_test_tfidf,
    "X:/AI-SPAM-PHISHING-DETECTOR/models/X_test.pkl"
)

joblib.dump(
    y_train,
    "X:/AI-SPAM-PHISHING-DETECTOR/models/y_train.pkl"
)

joblib.dump(
    y_test,
    "X:/AI-SPAM-PHISHING-DETECTOR/models/y_test.pkl"
)

print("Training and Testing data saved!")

Training and Testing data saved!